### PR TITLE
Fix ArcTo for iOS and Android platforms (with few tests)

### PR DESCRIPTION
**Pull request by SeeD-Seifer**
**ArcTo** didn't work correctly.
I've added a few tests and updated iOS and Android implementations.
You can see, that `ErulisseuiinSpaceshipPack.svg` test result is now better for iOS, though there is no improvement for Android (which is also good - it isn't worse).

There is no built-in method to draw elliptical arcs on iOS, so `ErulisseuiinSpaceshipPack.svg` result is not the same as a source file. I've not implemented any fix for this case, but the following workaround can help for the one who decides to fix it http://stackoverflow.com/questions/11365775/how-to-draw-an-elliptical-arc-with-coregraphics.

### CODE REVIEW

**Comment by praeclarum** [comment]
You deserve more than a thumbs up for this! Thank you so much for figuring it out - the arc stuff kills my brain.

And thanks for the tests! Those spaceships are getting close!

**Comment by SeeD-Seifer** [comment]
@praeclarum I'll try to take a look into this stuff further during the next weeks. This part is pretty interesting for my brain :)

The library is awesome! I'm heavily relying on it in one of the projects. So there is more stress-testing coming ;)

**Comment by woellij** [comment]
Thanks. I just ran into these issues displaying a gauge-like control on iOS.

With these fixes it works perfectly. Perfect timing too ;)

**Comment by kentcb** [comment]
@SeeD-Seifer Any explanation of how arc drawing actually works, as in how to figure out what to pass as parameters? I'm trying to port some SkiaSharp code to NGraphics as an experiment, and I can't for the life of me figure out how to port my arc calls.

Consider this code:
```C#
            renderContext
                .Canvas
                .DrawPath(
                    p =>
                    {
                        p.MoveTo(100, 150);
                        p.ArcTo(
                            radius: new Size(150, 200),
                            largeArc: false,
                            sweepClockwise: true,
                            point: new Point(200, 200));
                    },
                    pen: Pens.Black);
            renderContext
                .Canvas
                .DrawPath(
                    p =>
                    {
                        p.MoveTo(100, 150);
                        p.LineTo(new Point(200, 200));
                    },
                    pen: Pens.Green);
            renderContext
                .Canvas
                .DrawEllipse(
                    100,
                    150,
                    150,
                    200,
                    brush: new SolidBrush(Colors.Red.WithAlpha(0.5)));
```
Here's the render of this on Android:
image
Why doesn't the arc start and end at the same points as the line?

**Comment by kentcb** [comment]
Interestingly, it only seems to function as expected when the radius of the arc is circular, not elliptical.

**Comment by SeeD-Seifer** [comment]
@kentcb I didn't need to use ellipses so I didn't test it.
This line looks like a reason of the issue: https://github.com/praeclarum/NGraphics/blob/master/Platforms/NGraphics.Android/AndroidPlatform.cs#L340

**Comment by kentcb** [comment]
Yeah, have been playing around with that line and more. I can see that the bounding rectangle is moving down as the x radius of the arc increases. Just not sure I understand why yet, or what to do about it.

**Comment by kentcb** [comment]
I believe the problem is actually [these lines](https://github.com/praeclarum/NGraphics/blob/master/NGraphics/Path.cs#L165-L166). That is, `xd` and `yd` are the wrong way around. Certainly that looks to be the case from my testing, but I'll try it out more before submitting a PR.

**Pull request merged**
